<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span>My homework custom block!</span>
    </h1>

    <?php if ($block->getName() && $block->getLastname()):?>
        <h3>My mame is <?php echo $block->getName() . ' ' . $block->getLastname();?></h3>
    <?php endif;?>

    <?php if ($block->getJsonResponseUrl()):?>
        <a href="<?php echo $block->getJsonResponseUrl() ?>">Link to JSON controller</a>
    <?php endif;?>
</div>