<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<div class="actions dropdown example-dropdown-5">
    <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
        <span>span + dropdown</span>
    </span>
    <ul class="dropdown">
        <li>
            <span class="item">One</span>
        </li>
        <li>
            <span class="item">Two</span>
        </li>
        <li>
            <span class="item">Three</span>
        </li>
    </ul>
</div>