<div>
    <a href="#" id="dealer-registration"
       data-mage-init='{"dealerRegistration": {"title": "Registration for dealer"}}'>Registration for dealer</a>
</div>
<br>
<div id="dealer-registration-pop" style="display:none;">
    <div id="dealer-registration-pop-inner"></div>
</div>

<!--
<script type="text/x-magento-init">
    {
        "*": {
            "dealerRegistration": {
                "title":
                    "Registration for dealer"
            }
        }
    }
</script>
-->
