<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-wrapper">
    <h1>
        <span><?php echo __('Module Oop')?></span>
    </h1>

    <?php if ($diParams = $block->getDiParams()) : ?>
        <h2><?php echo __('DI Params')?></h2>
        <?php foreach ($diParams as $paramKey => $paramValue) : ?>
            <strong><?php echo __('Param Key')?>:</strong><br> <?php echo $paramKey; ?><br>
            <strong><?php echo __('Param Value')?>:</strong><br>
            <?php if (is_array($paramValue)) : ?>
                <?php foreach ($paramValue as $paramItemKey => $paramItemValue) : ?>
                    <?php echo $paramItemKey; ?> =>
                    <?php echo is_null($paramItemValue) ? 'null' : $paramItemValue; ?><br>
                <?php endforeach; ?>
            <?php else : ?>
                <?php echo is_null($paramValue) ? 'null' : $paramValue; ?><br>
            <?php endif; ?><br>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($methods = $block->getMethods()) : ?>
        <h2><?php echo __('Methods')?></h2>
        <?php foreach ($methods as $method) : ?>
            <div><?php echo $method->name; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($constants = $block->getConstants()) : ?>
        <h2><?php echo __('Constants')?></h2>
        <?php foreach ($constants as $constantName => $constantValue) : ?>
            <div><?php echo $constantName; ?> = <?php echo $constantValue; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($dirContents = $block->getDirContents()) : ?>
        <h2><?php echo __('Directories/files list')?></h2>
        <?php foreach ($dirContents as $item => $date) : ?>
            <div><?php echo $item; ?> (<?php echo $date; ?>)</div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>