<?php
/* @var $block \GorbanSv\CustomWidget\Block\Widget\Banner */
?>

<?php if ($block->getData('button_title')): ?>
    <button class="button-cms-page">
        <a href="<?php echo $block->getUrl('geekhub-cms') ?>"><?php echo $block->getData('button_title') ?></a>
    </button>
<?php endif; ?>

<?php if ($block->getData('cms_block')): ?>
    <?php echo $block->getLayout()
                     ->createBlock('Magento\Cms\Block\Block')
                     ->setBlockId($block->getData('cms_block'))
                     ->toHtml(); ?>
<?php endif; ?>
